package com.example.demo.domain.entities;

public enum GeneroFilme {

    ACAO, AVENTURA, COMEDIA, DANCA, DOCUMENTARIO, DRAMA, FANTASIA, FAROESTE, FICCAO_CIENTIFICA,
    MUSICAL, FILME_POLICIAL, SUSPENSE, TERROR;
}
